name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.27.0' # Atualizado para evitar downloads extras

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar Dependências
        run: |
          pip install -r requirements.txt
          pip install --upgrade flet 
          # Garante flet atualizado

      - name: Injetar API Key no .env
        env:
          CHAVE_SECRETA: ${{ secrets.API_KEY }} 
        run: |
          echo "API_KEY=$CHAVE_SECRETA" > .env

      - name: Compilar APK
        # O 'yes |' força o aceite (y) se o Flet perguntar algo
        run: |
          yes | flet build apk --verbose

      - name: Upload do APK
        uses: actions/upload-artifact@v4
        with:
          name: finantea-apk
          path: build/apk/app-release.apk
