name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configura o Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Configura o Java (Necessário para Android)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 4. Configura o Flutter (Motor do Flet Mobile)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      # 5. Instala o Flet e dependências
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install flet
          pip install fpdf
          # O dotenv foi removido do código, então não precisa instalar aqui

      # 6. Compila o APK
      - name: Build APK
        run: |
          flet build apk --verbose

      # 7. Salva o APK para download
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: finantea-app
          path: build/app/outputs/flutter-apk/app-release.apk
